package com.qa.exeptions;

public class ExceptionExample {

	public void multiplyException(int numOne,int numTwo) throws Exception {
		
		//if (numOne == 5 )
	}
}
